Comment out 2 parsers that cause 500 error
localhost:9000 now shows this Compilation error:
cannot find anorm.Column[_] nor anorm.RowParser[_] for name:net.wiringbits.common.models.BabyName in constructor Baby
In /home/nick/code/scala.js/fbn/server/src/main/scala/net/wiringbits/repositories/daos/package.scala:61

In babyParser:

Macro.parser[Baby] (